"""Marker job server — thin HTTP orchestrator, NO models loaded in-process.

Architecture (permanent fix for converter crashes/timeouts):

    uvicorn marker_server (this file) — ~100MB, can never OOM
      POST /jobs/{id}        → save file, spawn worker subprocess, enqueue
      GET  /jobs/{id}        → {status: pending|running|done|failed, error?}
      GET  /jobs/{id}/result → markdown output

    marker_worker (separate process, spawned per job)
      loads marker models, converts, writes result, exits
      hard timeout enforced by the parent → runaway jobs are killed

The HTTP server holds NO models. A conversion that OOMs or hangs dies alone
in its subprocess — the server survives and the job can be retried.
"""

from __future__ import annotations

import asyncio
import os
import uuid
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile

app = FastAPI()

JOBS_DIR = Path(os.environ.get("JOBS_DIR", "/app/jobs"))
JOBS_DIR.mkdir(parents=True, exist_ok=True)

CONVERT_SCRIPT = Path(os.environ.get("CONVERT_SCRIPT", "/app/convert_one.py"))
JOB_TIMEOUT = float(os.environ.get("JOB_TIMEOUT", "600"))
# Cap concurrent subprocesses — each loads ~5.4GB of models.
MAX_CONCURRENT = int(os.environ.get("MAX_CONCURRENT_JOBS", "1"))

# In-memory job registry: job_id -> subprocess + status
_jobs: dict[str, dict] = {}
_jobs_lock = asyncio.Lock()
_jobs_semaphore = asyncio.Semaphore(MAX_CONCURRENT)


@app.get("/health")
async def health() -> dict[str, str]:
    """Liveness — the server holds no models so it is always healthy."""
    return {"status": "ok"}


@app.post("/jobs/{job_id}")
async def submit_job(
    job_id: str,
    file: UploadFile = File(...),  # noqa: B008 — FastAPI dependency injection
    output_format: str = Form(default="markdown"),
    mode: str = Form(default="fast"),
    force_ocr: bool = Form(default=False),
) -> dict:
    """Accept a document, spawn an isolated conversion subprocess."""
    # Sanitize job_id — must be a hex id generated by the client.
    try:
        uuid.UUID(job_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="invalid job id") from None

    safe_name = Path(file.filename or "document").name
    input_path = JOBS_DIR / f"{job_id}_{safe_name}"
    result_path = JOBS_DIR / f"{job_id}.json"

    content = await file.read()
    input_path.write_bytes(content)
    result_path.unlink(missing_ok=True)

    async with _jobs_lock:
        if job_id in _jobs and _jobs[job_id]["status"] in ("pending", "running"):
            raise HTTPException(status_code=409, detail="job already running")

        _jobs[job_id] = {"status": "pending", "task": None}
        task = asyncio.create_task(
            _run_job(job_id, str(input_path), str(result_path), output_format, mode, force_ocr)
        )
        _jobs[job_id]["task"] = task

    return {"job_id": job_id, "status": "pending"}


@app.get("/jobs/{job_id}")
async def job_status(job_id: str) -> dict:
    """Poll job status: pending | running | done | failed."""
    result_path = JOBS_DIR / f"{job_id}.json"
    if result_path.exists():
        return {"job_id": job_id, "status": "done"}
    async with _jobs_lock:
        job = _jobs.get(job_id)
    if job is None:
        return {"job_id": job_id, "status": "done", "note": "result not found"}
    return {"job_id": job_id, "status": job["status"]}


@app.get("/jobs/{job_id}/result")
async def job_result(job_id: str) -> dict:
    """Fetch the conversion result (JSON with output/error)."""
    result_path = JOBS_DIR / f"{job_id}.json"
    if not result_path.exists():
        raise HTTPException(status_code=404, detail="result not ready")
    import json

    try:
        return json.loads(result_path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        raise HTTPException(status_code=500, detail=f"corrupt result: {exc}") from exc


async def _run_job(
    job_id: str,
    input_path: str,
    result_path: str,
    output_format: str,
    mode: str,
    force_ocr: bool,
) -> None:
    """Run one conversion in an isolated subprocess with a hard timeout.

    The subprocess loads marker models, converts, writes the result JSON and
    exits — freeing all memory. If it OOMs or hangs, only this subprocess
    dies; the server and other jobs are unaffected.
    """
    async with _jobs_semaphore:
        async with _jobs_lock:
            if job_id in _jobs:
                _jobs[job_id]["status"] = "running"

        cmd = [
            "python",
            str(CONVERT_SCRIPT),
            "--input", input_path,
            "--output", result_path,
            "--format", output_format,
            "--mode", mode,
        ]
        if force_ocr:
            cmd.append("--force-ocr")

        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            try:
                _, stderr = await asyncio.wait_for(proc.communicate(), timeout=JOB_TIMEOUT)
            except TimeoutError:
                proc.kill()
                await proc.wait()
                _write_result(
                    result_path,
                    {"success": False, "error": f"conversion timed out after {JOB_TIMEOUT:.0f}s"},
                )
                async with _jobs_lock:
                    if job_id in _jobs:
                        _jobs[job_id]["status"] = "failed"
                return

            if proc.returncode != 0:
                err = stderr.decode(errors="replace")[-1000:]
                _write_result(result_path, {"success": False, "error": err or "conversion subprocess failed"})
            # Success: convert_one.py already wrote the result JSON.
        except Exception as exc:
            _write_result(result_path, {"success": False, "error": f"server error: {exc}"})
        finally:
            async with _jobs_lock:
                if job_id in _jobs:
                    _jobs[job_id]["status"] = "done" if Path(result_path).exists() else "failed"
            # Clean up the uploaded input file.
            with __import__("contextlib").suppress(OSError):
                os.remove(input_path)


def _write_result(path: str, payload: dict) -> None:
    import json

    with __import__("contextlib").suppress(OSError):
        Path(path).write_text(json.dumps(payload))
